language: objective-c
osx_image: osx_image: xcode12.2
xcode_workspace: Latree.xcodeproj
xcode_scheme: Latree
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
before_install:
  - bundle install
  - bundle exec pod install --repo-update
