# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Latree' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Latree

  target 'LatreeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LatreeUITests' do
    # Pods for testing
  end

end
